experiment:
  seed: 42
  train_iters: 200000
  jit_loop: 1
  validate_every: 200
  save_every: 5000
  print_every: 100
dataset:
  basedir: data/nerf_synthetic/lego
  filter_chain:
    skiptest: 1
    downscale: 8
    white_background: False
  sampler:
    num_random_rays: 4096 # 4096
  projection:
    no_ndc: True
    near: 2
    far: 6
nerf:
  model:
    coarse:
      num_layers: 8
      hidden_size: 128
      skip_connect_every: 3
      num_encoding_fn_xyz: 10
      use_viewdirs: True
      num_encoding_fn_dir: 4
    fine:
      num_layers: 8
      hidden_size: 128
      skip_connect_every: 3
      num_encoding_fn_xyz: 10
      use_viewdirs: True
      num_encoding_fn_dir: 4
    optimizer:
      initial_lr: 5.0E-3
      lr_decay: 250
      lr_decay_factor: 0.1
  train:
    use_viewdirs: True
    num_random_rays: 1024
    chunksize: 131072 # 16192
    perturb: False
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 0.2
    lindisp: False
  validation:
    use_viewdirs: True
    chunksize: 16192 # 16192
    perturb: False
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 0.
    lindisp: False
sdrf:
  eikonal:
    scale: 2.0
    num_samples: 32768
  manifold:
    scale: 2.0
    num_samples: 32768
  sampler:
    kind: "stratified"
    linear:
      support: 5.0E-2
    stratified:
      support: 1.0E-1
    gaussian:
      sigma: 5.0E-2
  render:
    phi:
      initial_sigma: 1.0E-1
      lr_decay: 200
      lr_decay_factor: 0.01
    scale_factor:
      initial_sigma: 1.0
      lr_decay: 3
      lr_decay_factor: 0.9
    num_samples: 16
    truncation_distance: 0.5
    additive: True
    chunksize: 32768 # 4096
    isosurfaces_debug: False
    oryx_debug: False
  model:
    network:
      weight_file: "experiment/sphere_nerf.pkl"
      num_layers: 8
      hidden_size: 128
      skip_connect_every: 3
      num_encoding_fn_xyz: 6
      num_encoding_fn_dir: 4
    optimizer:
      initial_lr: 1.0E-4
      lr_decay: 10
      lr_decay_factor: 0.1